media: docs/assets

content:
  - name: Pages
    label: Pages
    path: docs
    type: collection
    fields:
      - {name: title, label: Title, type: string}
      - {name: description, label: Description, type: string}
     