media: assets 

content:
  - name: Contact
    label: Contact
    path: src/contact.json
    type: file
    fields:
      - name: selfIntro1
        label: SelfIntro1
        type: string

      - name: personal_information
        label: Personal_information
        type: string
        list: true


  - name: About
    label: About
    path: src/about.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string

  - name: Gallery
    label: Gallery
    path: src/gallery.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        
  - name: Index
    label: Index
    path: src/index.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        
  - name: Services
    label: Services
    path: src/services.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string

  
    