media: assets 

content:
  - name: About
    label: About
    path: pageCMS
    type: collection
    fields:
    - {name: description, label: description, type: string}
    - {name: buttonText, label: buttonText, type: string}
    - {name: background, label: background, type: string}
    - {name: ability, label: ability, type: string}
    - {name: personal_information_Birthday, label: personal_information_Birthday, type: number}
    - {name: personal_information_Age, label: personal_information_Age, type: number}