media: assets 

content:
  - name: Contact
    label: Contact
    path: src/contact.json
    type: file
    fields:
      - name: selfIntro1
        label: SelfIntro1
        type: string

      - name: Location
        label: Location
        type: string

      - name: Website
        label: Website
        type: string

      - name: Phone
        label: Phone
        type: string

      - name: Email
        label: Email
        type: string


  - name: About
    label: About
    path: src/about.json
    type: file
    fields:
      - name: description
        label: description
        type: string

      - name: buttonText
        label: buttonText
        type: string

      - name: background
        label: background
        type: string

      - name: ability
        label: ability
        type: string

      - name: Birthday
        label: Birthday 
        type: text

      - name: Age
        label: Age 
        type: text

      - name: Website
        label: Website 
        type: text

      - name: Degree
        label: Degree 
        type: text

      - name: Phone
        label: Phone 
        type: text

      - name: Email
        label: Email 
        type: text

      - name: City
        label: City 
        type: text

      - name: Freelance
        label: Freelance 
        type: text

      - name: selfIntro1
        label: selfIntro1 
        type: text

      - name: selfIntro2
        label: selfIntro2 
        type: text


  - name: Gallery
    label: Gallery
    path: src/gallery.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        
  - name: Index
    label: Index
    path: src/index.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        
  - name: Services
    label: Services
    path: src/services.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string

  
    