media: assets 

content:
  - name: Contact
    label: Contact
    path: JSON/contact.json
    type: file
    fields:
      - name: selfIntro1
        label: SelfIntro1
        type: string

      - name: Location
        label: Location
        type: string

      - name: Website
        label: Website
        type: string

      - name: Phone
        label: Phone
        type: string

      - name: Email
        label: Email
        type: string


  - name: About
    label: About
    path: src/about.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string

  - name: Gallery
    label: Gallery
    path: src/gallery.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        
  - name: Index
    label: Index
    path: src/index.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        
  - name: Services
    label: Services
    path: src/services.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string

  
    