name: CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build-html.js (services.json, services.template.html, footer.html -> services.html)
        run: node build-html.js services.json services.template.html footer.html services.html

      - name: Run build-html.js (index.json, index.template.html, footer.html -> index.html)
        run: node build-html.js index.json index.template.html footer.html index.html
      
      - name: Run build-html.js (about.json, about.template.html, footer.html -> about.html)
        run: node build-html.js about.json about.template.html footer.html about.html

      - name: Run build-html.js (contact.json, contact.template.html, footer.html -> contact.html)
        run: node build-html.js contact.json contact.template.html footer.html contact.html

      - name: Run build-html.js (gallery.json, gallery.template.html, footer.html -> gallery.html)
        run: node build-html.js gallery.json gallery.template.html footer.html gallery.html

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: HTML
        FOLDER: HEADER, JSON, html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        