name: CI

on:
  push:
    branches: 
      - main 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Build Website
        run: |
          npm install
          npm run build_website
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy HTML to GitHub Pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: HTML
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
